/*
 * ADC_Config.h
 *
 *  Created on: Feb 17, 2024
 *      Author: samar ibrahim
 */

#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_

/*VREF OF ADC USE CAN CHOOSE (AVREF,AVCC,INTERNAL_VREF)*/
#define ADC_VREF        AVCC_REF

/*adjustment OF ADC USE CAN CHOOSE ( RIGHT_ADJUST , LEFT_ADJUST )*/
#define ADC_ADJUST       RIGHT_ADJUST

/*Prescaler OF ADC USE CAN CHOOSE ( DIVISION_FACTOR_2,DIVISION_FACTOR_4,DIVISION_FACTOR_8,DIVISION_FACTOR_16,DIVISION_FACTOR_32,DIVISION_FACTOR_64,DIVISION_FACTOR_128 )*/
#define ADC_PRESCALER   DIVISION_FACTOR_8
#endif /* MCAL_ADC_ADC_CONFIG_H_ */
